dic = {
            'prices': '价格',
            'RANGE': '射程',
            'DAMAGE': '伤害',
            'ATTACK_SPEED': '攻击速度',
            'ROTATION_SPEED': '旋转速度',
            'PROJECTILE_SPEED': '子弹速度',
            'U_BURN_CHANCE': '燃烧机率',
            'U_BURNING_TIME': '燃烧时间',
            'U_DAMAGE_MULTIPLY': '伤害加成',
            'STUN_CHANCE': '眩晕机率',
            'U_STUN_DURATION': '眩晕时间',
            'U_EXPLOSION_RANGE': '爆炸范围',
            'FREEZE_PERCENT': '冰冻机率',
            'FREEZE_SPEED': '冰冻速度',
            'U_POISON_DURATION_BONUS': '中毒时间',
            'U_CHAIN_LIGHTNING_BONUS_LENGTH': '链电长度',
            'U_BATTERIES_CAPACITY': '电池容量',
            'U_ACCELERATION': '加速度',
            'U_PROJECTILE_COUNT': '子弹数量',
            'U_SHOOT_ANGLE': '射击角度',
            'AIM_SPEED': '瞄准速度',
            'U_CRIT_CHANCE': '暴击机率',
            'U_CRIT_MULTIPLIER': '暴击加成',
            'ACCURACY': '精准度',
            'CHAIN_LIGHTNING_DAMAGE': '链电伤害',
            'U_CHAIN_LIGHTNING_LENGTH': '链电长度',
            'U_POISON_DURATION': '中毒时间',
            'RESOURCE_CONSUMPTION': '资源消耗',
            'CHARGING_SPEED': '充能速度',
            'DURATION': '持续时间',
            'U_BONUS_EXPERIENCE': '经验加成',
            'U_LRM_AIM_SPEED': '瞄准速度',
        }
for k,v in dic.items():
    print(f'"{v}": "{k}",')
setHorizontalHeaders(self, labels:List)