dic = {
    "基础塔": "BASIC",
    "狙击塔": "SNIPER",
    "加农炮": "CANNON",
    "寒冰塔": "FREEZING",
    "防空塔": "AIR",
    "溅射塔": "SPLASH",
    "爆破塔": "BLAST",
    "散射塔": "MULTISHOT",
    "机枪塔": "MINIGUN",
    "毒液塔": "VENOM",
    "特斯拉": "TESLA",
    "导弹": "MISSILE",
    "火焰塔": "FLAME",
    "激光塔": "LASER",
    "电磁炮": "GAUSS",
    "破碎机": "CRUSHER",
}
for k,v in dic.items():
    print(f'"{v}": "{k}",')
towerNameEngZh = {
            "BASIC": "基础塔",
            "SNIPER": "狙击塔",
            "CANNON": "加农炮",
            "FREEZING": "寒冰塔",
            "AIR": "防空塔",
            "SPLASH": "溅射塔",
            "BLAST": "爆破塔",
            "MULTISHOT": "散射塔",
            "MINIGUN": "机枪塔",
            "VENOM": "毒液塔",
            "TESLA": "特斯拉",
            "MISSILE": "导弹",
            "FLAME": "火焰塔",
            "LASER": "激光塔",
            "GAUSS": "电磁炮",
            "CRUSHER": "破碎机",
        }